services:

  backend:
    build:
      context: ./finance-backend
    container_name: pocketflow-backend

    ports:
      - "8000:8000"

    volumes:
      - ./finance-backend:/app

    restart: unless-stopped

  frontend:
    build:
      context: ./finance-dashboard
    container_name: pocketflow-frontend

    ports:
      - "3000:3000"

    volumes:
      - ./finance-dashboard:/app
      - /app/node_modules

    depends_on:
      - backend

    restart: unless-stopped
