name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Backend Image
        run: |
          docker build \
            -t pocketflow-backend \
            ./finance-backend

      - name: Tag Backend Image
        run: |
          docker tag pocketflow-backend:latest \
          831959027398.dkr.ecr.us-east-1.amazonaws.com/pocketflow-backend:latest

          docker tag pocketflow-backend:latest \
          831959027398.dkr.ecr.us-east-1.amazonaws.com/pocketflow-backend:${{ github.sha }}

      - name: Push Backend Image
        run: |
          docker push 831959027398.dkr.ecr.us-east-1.amazonaws.com/pocketflow-backend:latest

          docker push 831959027398.dkr.ecr.us-east-1.amazonaws.com/pocketflow-backend:${{ github.sha }}

      - name: Build Frontend Image
        run: |
          docker build \
            -t pocketflow-frontend \
            ./finance-dashboard

      - name: Tag Frontend Image
        run: |
          docker tag pocketflow-frontend:latest \
          831959027398.dkr.ecr.us-east-1.amazonaws.com/pocketflow-frontend:latest

          docker tag pocketflow-frontend:latest \
          831959027398.dkr.ecr.us-east-1.amazonaws.com/pocketflow-frontend:${{ github.sha }}

      - name: Push Frontend Image
        run: |
          docker push 831959027398.dkr.ecr.us-east-1.amazonaws.com/pocketflow-frontend:latest

          docker push 831959027398.dkr.ecr.us-east-1.amazonaws.com/pocketflow-frontend:${{ github.sha }}  